# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# on:  
#   schedule:    
#     - cron: 0 12 * * *
      
jobs:
  grabData:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wget
#       run: |
#         python -m pip install --upgrade pip
#         pip install flake8 pytest
#         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#     - name: Lint with flake8
#       run: |
#         # stop the build if there are Python syntax errors or undefined names
#         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Grab the data
      run: |
        python grab_data.py
        
    - name: git check in
      env:
          GIT_OWNER_EMAIL: ${{ secrets.GIT_OWNER_EMAIL }} 
          PUSH_TOKEN: ${{secrets.PUSH_TOKEN}}
      run: |
          git config --global user.email "kinjalrk2k@gmail.com"
          git config --global user.name "Kinjalrk2k"
          if [[ `git status --porcelain` ]]; then
            git add .
            git checkout master
            git commit -a -m "Data update on `date +'%Y-%m-%d %H:%M:%S'`"
            git remote add origin https://Kinjalrk2k:$PUSH_TOKEN@https://github.com/Kinjalrk2k/COVID-19.git
            git push origin HEAD:master
          else
            echo 'unable to detect changes'
